insert into campain_details(
    id,
    profilierungssortiment,
    kundengruppe,
    label,
    marke,
    industrie,
    organisation,
    gM,
    update,
    planumsatz,
    projektleiter,
    erfassergruppe,
    bezeichnungsprache,
    bezeichnung,
    kampagnesprache,
    kampagnename,
    mABEOnly,
    ende,
    start,
    kampagnentyp,
    ext_kampagnenid,
    transaktionsID,
    quell_system)

values(   1001,
          '',
          '',
          '',
          '',
          '',
          '02 03 09 99',
          'MGB',
          '0',
          '',
          'salomon.guttmann@mgb.ch',
          'MGB',
          'D',
          '',
          'D',
          '270200-PEMA Migusto NL',
          '0',
          '20260305',
          '20260407',
          'CDM',
          'KAMP_40352',
          '001',
          '2');

insert into campain_details(
    id,
    profilierungssortiment,
    kundengruppe,
    label,
    marke,
    industrie,
    organisation,
    gM,
    update,
    planumsatz,
    projektleiter,
    erfassergruppe,
    bezeichnungsprache,
    bezeichnung,
    kampagnesprache,
    kampagnename,
    mABEOnly,
    ende,
    start,
    kampagnentyp,
    ext_kampagnenid,
    transaktionsID,
    quell_system)

values(   1002,
          '',
          '',
          '',
          '',
          '',
          '02 03 09 99',
          'MGB',
          '0',
          '',
          'salomon.guttmann@mgb.ch',
          'MGB',
          'D',
          '',
          'D',
          '270201-PEMA Misgustos NL',
          '0',
          '20260305',
          '20260407',
          'CDM',
          'KAMP_40353',
          '001',
          '2');

insert into campain_details(
    id,
    profilierungssortiment,
    kundengruppe,
    label,
    marke,
    industrie,
    organisation,
    gM,
    update,
    planumsatz,
    projektleiter,
    erfassergruppe,
    bezeichnungsprache,
    bezeichnung,
    kampagnesprache,
    kampagnename,
    mABEOnly,
    ende,
    start,
    kampagnentyp,
    ext_kampagnenid,
    transaktionsID,
    quell_system)

values(   1003,
          '',
          '',
          '',
          '',
          '',
          '02 03 09 99',
          'MGB',
          '0',
          '',
          'salomon.guttmann@mgb.ch',
          'MGB',
          'D',
          '',
          'D',
          '270202-PEMA Misgustos NL',
          '0',
          '20260305',
          '20260407',
          'CDM',
          'KAMP_40354',
          '001',
          '2');