package com.rest.webservices.restfulwebservices.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2026-02-02T10:33:18.352+01:00
 * Generated source version: 4.0.4
 *
 */
@WebServiceClient(name = "SI_OS_CampaignService",
                  wsdlLocation = "file:/home/salomon/developer/MasterMicroservices/MasterMicroservicesTraining/campain-web-services/src/main/resources/META-INF/SI_OS_Campaign_D99.wsdl",
                  targetNamespace = "http://sas.com/customerintelligence")
public class SIOSCampaignService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://sas.com/customerintelligence", "SI_OS_CampaignService");
    public static final QName SIOSCampaignPort = new QName("http://sas.com/customerintelligence", "SI_OS_CampaignPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/salomon/developer/MasterMicroservices/MasterMicroservicesTraining/campain-web-services/src/main/resources/META-INF/SI_OS_Campaign_D99.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SIOSCampaignService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/salomon/developer/MasterMicroservices/MasterMicroservicesTraining/campain-web-services/src/main/resources/META-INF/SI_OS_Campaign_D99.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SIOSCampaignService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SIOSCampaignService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIOSCampaignService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SIOSCampaignService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SIOSCampaignService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SIOSCampaignService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SIOSCampaign
     */
    @WebEndpoint(name = "SI_OS_CampaignPort")
    public SIOSCampaign getSIOSCampaignPort() {
        return super.getPort(SIOSCampaignPort, SIOSCampaign.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIOSCampaign
     */
    @WebEndpoint(name = "SI_OS_CampaignPort")
    public SIOSCampaign getSIOSCampaignPort(WebServiceFeature... features) {
        return super.getPort(SIOSCampaignPort, SIOSCampaign.class, features);
    }

}
