package com.rest.webservices.restfulwebservices.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2026-02-02T10:33:18.347+01:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://sas.com/customerintelligence", name = "SI_OS_Campaign")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIOSCampaign {

    @WebMethod(operationName = "SI_OS_Campaign", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ImportCampaign_Res", targetNamespace = "http://sas.com/customerintelligence", partName = "MT_ImportCampaign_Res")
    public DTImportCampaignRes siOSCampaign(

        @WebParam(partName = "MT_ImportCampaign_Req", name = "MT_ImportCampaign_Req", targetNamespace = "http://sas.com/customerintelligence")
        DTImportCampaignReq mtImportCampaignReq
    );
}
