
package com.rest.webservices.restfulwebservices.wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2026-02-02T10:33:18.290+01:00
 * Generated source version: 4.0.4
 *
 */
public final class SIOSCampaign_SIOSCampaignPort_Client {

    private static final QName SERVICE_NAME = new QName("http://sas.com/customerintelligence", "SI_OS_CampaignService");

    private SIOSCampaign_SIOSCampaignPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SIOSCampaignService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SIOSCampaignService ss = new SIOSCampaignService(wsdlURL, SERVICE_NAME);
        SIOSCampaign port = ss.getSIOSCampaignPort();

        {
        System.out.println("Invoking siOSCampaign...");
        com.rest.webservices.restfulwebservices.wsdl.DTImportCampaignReq _siOSCampaign_mtImportCampaignReq = null;
        com.rest.webservices.restfulwebservices.wsdl.DTImportCampaignRes _siOSCampaign__return = port.siOSCampaign(_siOSCampaign_mtImportCampaignReq);
        System.out.println("siOSCampaign.result=" + _siOSCampaign__return);


        }

        System.exit(0);
    }

}
